# Generated by Django 5.2.5 on 2025-10-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("path", models.CharField(max_length=512)),
                ("referer", models.CharField(blank=True, max_length=512, null=True)),
                ("source", models.CharField(default="Direct", max_length=50)),
                ("device", models.CharField(default="unknown", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pageview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.pageview",
                    ),
                ),
            ],
        ),
    ]
