# Generated by Django 5.2.5 on 2025-11-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_pageview_visitor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageview",
            name="visitor_id",
        ),
    ]
