# Generated by Django 5.2.5 on 2026-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_pageview_visitor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("visitor_id", models.CharField(blank=True, max_length=64, null=True)),
                ("collection", models.CharField(db_index=True, max_length=100)),
                ("path", models.CharField(max_length=255)),
                ("source", models.CharField(default="direct", max_length=50)),
                ("device", models.CharField(default="unknown", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField(default=0.0)),
            ],
        ),
    ]
