# Generated by Django 5.2.5 on 2025-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="height_cm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="weight_kg",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
