# Generated by Django 5.2.5 on 2025-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_subscriber_height_cm_subscriber_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="personalized_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
