# Generated by Django 5.2.5 on 2025-09-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("hero_title", models.CharField(blank=True, max_length=120)),
                ("hero_subtitle", models.CharField(blank=True, max_length=300)),
                ("hero_cta_text", models.CharField(blank=True, max_length=40)),
                ("hero_cta_url", models.CharField(blank=True, max_length=200)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/hero/"),
                ),
                ("newsletter_title", models.CharField(blank=True, max_length=120)),
                ("newsletter_subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "newsletter_button",
                    models.CharField(blank=True, default="Prenumeruoti", max_length=40),
                ),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "verbose_name": "Titulinis",
                "verbose_name_plural": "Titulinis",
            },
        ),
        migrations.CreateModel(
            name="HomeTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=80)),
                ("alt_text", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="pages/tiles/")),
                (
                    "link_url",
                    models.CharField(
                        help_text='Pvz. "/shop/" arba "/product/<slug>/"',
                        max_length=200,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[("s", "Maža"), ("m", "Vidutinė"), ("l", "Didelė")],
                        default="m",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="pages.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
