# Generated by Django 5.2.5 on 2025-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_homepage_hometile"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_note",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
