# Generated by Django 5.2.5 on 2025-09-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_homepage_hero_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hometile",
            options={
                "ordering": ["order"],
                "verbose_name": "Plytelė",
                "verbose_name_plural": "Galerija (plytelės)",
            },
        ),
        migrations.AddField(
            model_name="hometile",
            name="label_pos",
            field=models.CharField(
                choices=[
                    ("bl", "Apačia-kairė"),
                    ("br", "Apačia-dešinė"),
                    ("tl", "Viršus-kairė"),
                    ("tr", "Viršus-dešinė"),
                    ("cc", "Centras"),
                ],
                default="bl",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="hometile",
            name="link_url",
            field=models.CharField(
                help_text='Pvz. "/shop/" arba "/category/<slug>/"', max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="hometile",
            name="variant",
            field=models.CharField(
                choices=[
                    ("s", "1×1 (maža)"),
                    ("m", "2×1 (plati)"),
                    ("t", "1×2 (aukšta)"),
                    ("l", "3×2 (didelė)"),
                ],
                default="m",
                max_length=10,
            ),
        ),
    ]
