# Generated by Django 5.2.5 on 2025-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_hometile_options_hometile_label_pos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="email",
            new_name="owner_email",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="phone",
            new_name="owner_phone",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="tiktok",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="newsletter_button",
            field=models.CharField(blank=True, default="Prenumeruoti", max_length=40),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="newsletter_placeholder",
            field=models.CharField(blank=True, default="El. paštas", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="newsletter_title",
            field=models.CharField(
                blank=True, default="Mūsų drabužių naujienos", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="owner_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_url",
            field=models.CharField(
                blank=True, help_text='Pvz. "/privacy/"', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="returns_url",
            field=models.CharField(
                blank=True, help_text='Pvz. "/returns/"', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shipping_url",
            field=models.CharField(
                blank=True, help_text='Pvz. "/shipping/"', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="terms_url",
            field=models.CharField(
                blank=True,
                help_text='Pvz. "/terms/" arba "/pages/pirkimo-taisykles/"',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vat_code",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
