# Generated by Django 5.2.5 on 2025-09-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_rename_email_sitesettings_owner_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="hero_alt",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="sidebar_main_video_poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="pages/video_posters/"
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="sidebar_main_video_url",
            field=models.URLField(blank=True, help_text="Pilnas YouTube/Vimeo URL"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="newsletter_placeholder",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="newsletter_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="privacy_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="returns_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="shipping_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="terms_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="vat_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="BrandStripItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80)),
                ("logo", models.ImageField(upload_to="pages/brands/")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text='Pvz. "/shop/" arba "https://..."',
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_items",
                        to="pages.staticpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=80)),
                ("image", models.ImageField(upload_to="pages/banners/")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text='Pvz. "/shop/" arba "https://..."',
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="pages.staticpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
