# Generated by Django 5.2.5 on 2025-09-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_sitesettings_email_sitesettings_phone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrandStripItem",
        ),
    ]
