# Generated by Django 5.2.5 on 2025-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketingPopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Popup administracinis pavadinimas", max_length=200
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Popup antraštė (rodančiame lange)", max_length=255
                    ),
                ),
                ("message", models.TextField(help_text="Popup tekstas arba HTML")),
                (
                    "delay_seconds",
                    models.PositiveIntegerField(
                        default=2000, help_text="Po kiek ms rodyti (1000 ms = 1s)"
                    ),
                ),
                (
                    "hide_after_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Po kiek ms paslėpti (0 = neslėpti automatiškai)",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Ar šis popup įjungtas?"
                    ),
                ),
                (
                    "for_product_page",
                    models.BooleanField(
                        default=True, help_text="Rodyti produkto puslapiuose?"
                    ),
                ),
                (
                    "for_catalog_page",
                    models.BooleanField(
                        default=False, help_text="Rodyti katalogo puslapiuose?"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Mažesnis skaičius = aukštesnis prioritetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketingo popup",
                "verbose_name_plural": "Marketingo popup'ai",
                "ordering": ["priority"],
            },
        ),
    ]
