# Generated by Django 5.2.5 on 2025-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingpopup",
            name="active",
            field=models.BooleanField(default=True, help_text="Ar popup įjungtas?"),
        ),
        migrations.AlterField(
            model_name="marketingpopup",
            name="delay_seconds",
            field=models.PositiveIntegerField(
                default=5, help_text="Po kiek sekundžių rodyti popup (pvz. 5)"
            ),
        ),
        migrations.AlterField(
            model_name="marketingpopup",
            name="hide_after_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Po kelių sekundžių paslėpti (0 = neslėpti automatiškai)",
            ),
        ),
        migrations.AlterField(
            model_name="marketingpopup",
            name="message",
            field=models.TextField(
                help_text="Popup modal'o turinys (tekstui arba HTML)"
            ),
        ),
        migrations.AlterField(
            model_name="marketingpopup",
            name="priority",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Mažesnis prioritetas = rodomas anksčiau rotacijoje",
            ),
        ),
        migrations.AlterField(
            model_name="marketingpopup",
            name="title",
            field=models.CharField(
                help_text="Popup antraštė (trigger mygtuke)", max_length=255
            ),
        ),
    ]
