# Generated by Django 5.2.5 on 2025-12-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_marketingpopup_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Popup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pop-up pavadinimas (adminui)", max_length=100
                    ),
                ),
                ("text", models.TextField(help_text="Tekstas, rodomas pop-upe")),
                (
                    "delay_ms",
                    models.PositiveIntegerField(
                        default=3000,
                        help_text="Po kiek milisekundžių rodyti (pvz., 5000 = 5s)",
                    ),
                ),
                (
                    "auto_close_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Po kiek milisekundžių automatiškai užsidaro (0 = niekada)",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Ar pop-upas įjungtas?"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifikatorius pop-upo (pvz: 'product-popup')",
                        unique=True,
                    ),
                ),
                ("show_on_product_page", models.BooleanField(default=True)),
                ("show_on_homepage", models.BooleanField(default=False)),
                ("show_on_category_page", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Popup",
                "verbose_name_plural": "Popup'ai",
            },
        ),
        migrations.DeleteModel(
            name="MarketingPopup",
        ),
    ]
