# Generated by Django 5.2.5 on 2025-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_popup_delete_marketingpopup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingPopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("delay_seconds", models.PositiveIntegerField(default=5)),
                ("hide_after_seconds", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("for_product_page", models.BooleanField(default=True)),
                ("for_catalog_page", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.DeleteModel(
            name="Popup",
        ),
    ]
