# Generated by Django 5.2.5 on 2025-12-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_marketingpopup_delete_popup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        default="popup",
                        help_text="Pvz: popup_shop, popup_blog, popup_product",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "popup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Iš kurio popup gautas leadas",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="marketing.marketingpopup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
