# Generated by Django 5.2.5 on 2026-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_popuplead"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivatePresentationLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "city",
                    models.CharField(
                        choices=[("vilnius", "Vilnius"), ("kaunas", "Kaunas")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="landing", max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
