# Generated by Django 5.2.5 on 2026-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_privatepresentationlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivatePageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
