# Generated by Django 5.2.5 on 2025-09-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Blog settings",
                "verbose_name_plural": "Blog settings",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="card_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
        migrations.AddField(
            model_name="post",
            name="card_variant",
            field=models.CharField(
                choices=[("small", "Maža"), ("large", "Didesnė")],
                default="small",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name="BrandItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="blog.blogsettings",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
