# Generated by Django 5.2.5 on 2025-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogsettings_post_card_image_post_card_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogsettings",
            name="must_read_title",
            field=models.CharField(blank=True, default="MUST READ", max_length=80),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="singleton",
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="ticker_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="ticker_separator",
            field=models.CharField(
                default="•",
                help_text="Skirtukas tarp brandų (pvz. • | /)",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="blogsettings",
            name="ticker_speed",
            field=models.PositiveIntegerField(
                default=30, help_text="Greitis (naudojamas FE animacijai)."
            ),
        ),
    ]
