# Generated by Django 5.2.5 on 2025-09-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogsettings_must_read_title_blogsettings_singleton_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogsettings",
            name="hero_subtitle",
        ),
    ]
