# Generated by Django 5.2.5 on 2025-09-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogsettings_hero_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
    ]
