# Generated by Django 5.2.5 on 2025-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_excerpt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Trumpas aprašymas (160–320 simbolių) SEO ir socialiniams tinklams.",
                max_length=320,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Jei tuščia, bus naudojamas straipsnio pavadinimas.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="show_in_separate_page",
            field=models.BooleanField(
                default=False,
                help_text="Pažymėjus – straipsnis atsidarys atskirame puslapyje.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
