# Generated by Django 5.2.5 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="show_in_separate_page",
            field=models.BooleanField(
                default=False,
                help_text="Pažymėjus – straipsnis atsidarys atskirame puslapyje.",
            ),
        ),
    ]
