# Generated by Django 5.2.5 on 2025-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_show_in_separate_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Trumpas aprašymas (160–320 simbolių) SEO ir socialiniams tinklams.",
                max_length=320,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Jei tuščia, bus naudojamas straipsnio pavadinimas.",
                max_length=255,
            ),
        ),
    ]
