# Generated by Django 5.2.5 on 2025-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_meta_description_post_meta_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="post",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
