# Generated by Django 5.2.5 on 2025-11-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_options_post_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["sort_order", "id"]},
        ),
    ]
