# Generated by Django 5.2.5 on 2025-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at", "id"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
