# Generated by Django 5.2.5 on 2025-11-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_options_alter_post_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="sort_order",
        ),
    ]
