# Generated by Django 5.2.5 on 2025-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_post_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="post",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
