# Generated by Django 5.2.5 on 2025-09-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Mokėjimas kurjeriui"),
                    ("paysera", "Paysera"),
                    ("stripe", "Stripe"),
                ],
                default="cod",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Laukiama apmokėjimo"),
                    ("cod_placed", "Pateiktas (COD)"),
                    ("paid", "Apmokėta"),
                    ("failed", "Nepavyko"),
                    ("canceled", "Atšaukta"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
