# Generated by Django 5.2.5 on 2025-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_payment_method_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_pi_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
