# Generated by Django 5.2.5 on 2025-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_stripe_pi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dpd_pickup_addr",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dpd_pickup_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dpd_pickup_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("dpd_courier", "DPD kurjeris"),
                    ("dpd_pickup", "DPD paštomatas"),
                ],
                default="dpd_courier",
                max_length=30,
            ),
        ),
    ]
