# Generated by Django 5.2.5 on 2025-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_stripe_pi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
