# Generated by Django 5.2.5 on 2025-10-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_dpd_pickup_addr_order_dpd_pickup_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
