# Generated by Django 5.2.5 on 2025-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_order_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="needs_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
