# Generated by Django 5.2.5 on 2025-09-18 08:21

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="hover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=catalog.models.product_upload_to
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=catalog.models.product_upload_to
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Iki 4 susijusių prekių",
                related_name="related_to",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=catalog.models.product_upload_to),
        ),
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
