# Generated by Django 5.2.5 on 2025-09-18 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Sugeneruojamas automatiškai",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^UR\\d{4}$", "SKU formatas: UR0001–UR9999"
                    )
                ],
            ),
        ),
    ]
