# Generated by Django 5.2.5 on 2025-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hover_image_alt",
            field=models.CharField(
                blank=True,
                help_text="ALT tekstas antroje produkto nuotraukai (rodoma ant hover)",
                max_length=255,
                verbose_name="Hover image ALT",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image_alt",
            field=models.CharField(
                blank=True,
                help_text="ALT tekstas pagrindinei produkto nuotraukai (SEO aprašymas)",
                max_length=255,
                verbose_name="Main image ALT",
            ),
        ),
    ]
