# Generated by Django 5.2.5 on 2025-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_hover_image_alt_product_main_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_model",
            field=models.BooleanField(
                default=False,
                help_text="Pažymėkite, jei pagrindinė produkto nuotrauka yra ant modelio (žmogaus).",
                verbose_name="Produktas ant modelio",
            ),
        ),
    ]
