# Generated by Django 5.2.5 on 2026-03-07 10:03

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_on_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="zoom_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=catalog.models.product_upload_to
            ),
        ),
    ]
