# Generated by Django 5.2.5 on 2026-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_privatecollection_privateproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateproduct",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
