# Generated by Django 5.2.5 on 2025-10-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TryOnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("height_cm", models.PositiveIntegerField()),
                ("weight_kg", models.PositiveIntegerField()),
                ("terms_accepted", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("items_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
