# Generated by Django 5.2.5 on 2025-10-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tryonrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Try-on užklausa",
                "verbose_name_plural": "Try-on užklausos",
            },
        ),
    ]
