# Generated by Django 5.2.5 on 2026-04-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_tryonrequest_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tryonrequest",
            name="height_cm",
        ),
        migrations.RemoveField(
            model_name="tryonrequest",
            name="weight_kg",
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tryonrequest",
            name="name",
            field=models.CharField(default="-", max_length=120),
            preserve_default=False,
        ),
    ]
