# Generated by Django 5.2.5 on 2025-12-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "title_url",
                    models.URLField(
                        blank=True,
                        help_text="Jeigu įvesi URL – pavadinimas taps nuoroda",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tips", "Urock ir vertė"),
                            ("collection", "Drabužiai ir įvaizdis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cloudflare_id",
                    models.CharField(
                        help_text="Cloudflare VIDEO id arba full HLS URL",
                        max_length=200,
                    ),
                ),
                (
                    "cover_desktop",
                    models.ImageField(
                        blank=True,
                        help_text="Desktop viršelis (rekomenduojama 1112×940)",
                        null=True,
                        upload_to="video_covers/desktop/",
                    ),
                ),
                (
                    "cover_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="Mobilus viršelis (rekomenduojama 400×400)",
                        null=True,
                        upload_to="video_covers/mobile/",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
