# Generated by Django 5.2.5 on 2025-11-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tips", "Stiliaus patarimai"),
                            ("collection", "Kolekcija"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cloudflare_id",
                    models.CharField(
                        help_text="Cloudflare VIDEO id arba full HLS URL",
                        max_length=200,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        help_text="Viršelio nuotrauka (Cloudflare thumbnail ar bet koks paveiksliukas)",
                        upload_to="video_covers/",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
