# Generated by Django 5.2.5 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="cover",
        ),
        migrations.AddField(
            model_name="video",
            name="cover_desktop",
            field=models.ImageField(
                blank=True,
                help_text="Desktop viršelis (rekomenduojama 1112×940)",
                null=True,
                upload_to="video_covers/desktop/",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="cover_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Mobilus viršelis (rekomenduojama 400×400)",
                null=True,
                upload_to="video_covers/mobile/",
            ),
        ),
    ]
