# Generated by Django 5.2.5 on 2025-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_remove_video_cover_video_cover_desktop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="label_url",
            field=models.URLField(
                blank=True,
                help_text="Jeigu įvesi URL – label taps aktyvia nuoroda.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("tips", "Urock ir vertė"),
                    ("collection", "Drabužiai ir įvaizdis"),
                ],
                max_length=20,
            ),
        ),
    ]
