# Generated by Django 5.2.5 on 2025-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_video_label_url_alter_video_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="label_url",
        ),
        migrations.AddField(
            model_name="video",
            name="title_url",
            field=models.URLField(
                blank=True,
                help_text="Jeigu įvesi URL – TITLE taps aktyvia nuoroda.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cloudflare_id",
            field=models.CharField(
                help_text="Cloudflare VIDEO ID arba full HLS URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cover_desktop",
            field=models.ImageField(
                blank=True,
                help_text="Desktop viršelis (1112×940)",
                null=True,
                upload_to="video_covers/desktop/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cover_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Mobilus viršelis (~400×400)",
                null=True,
                upload_to="video_covers/mobile/",
            ),
        ),
    ]
