# Generated by Django 5.2.5 on 2025-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_remove_video_label_url_video_title_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cloudflare_id",
            field=models.CharField(
                help_text="Cloudflare VIDEO id arba full HLS URL", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cover_desktop",
            field=models.ImageField(
                blank=True,
                help_text="Desktop viršelis (rekomenduojama 1112×940)",
                null=True,
                upload_to="video_covers/desktop/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cover_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Mobilus viršelis (rekomenduojama 400×400)",
                null=True,
                upload_to="video_covers/mobile/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title_url",
            field=models.URLField(
                blank=True,
                help_text="Jeigu įvesi URL – pavadinimas taps nuoroda",
                max_length=500,
            ),
        ),
    ]
